import type { FinancialService } from '../types/service';

export const MOCK_SERVICES: FinancialService[] = [
    {
        id: 'svc-001',
        category: 'SCORE_CREDITICIO',
        title: 'Consulta de Score Crediticio',
        description: 'Conoce tu puntaje crediticio actualizado en segundos.',
        longDescription: 'Obtén un reporte detallado de tu historial crediticio. Incluye puntaje actual, factores que lo afectan, recomendaciones para mejorar tu score y comparación con el promedio nacional. Útil antes de solicitar créditos o préstamos.',
        icon: '📈',
        price: 0,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '1 minuto',
        requirements: ['DNI vigente', 'Número de celular verificado'],
        tags: ['Gratuito', 'Inmediato', 'Crédito'],
        rating: 4.8,
        reviewCount: 1243,
    },
    {
        id: 'svc-002',
        category: 'COMPRA_DIVISAS',
        title: 'Compra de Divisas',
        description: 'Compra dólares, euros y otras monedas a tasas competitivas.',
        longDescription: 'Compra monedas extranjeras desde tu cuenta sin salir de casa. Tasas actualizadas en tiempo real, sin comisiones ocultas. Soporta USD, EUR, GBP y BRL. El monto se descuenta automáticamente de tu cuenta en Soles.',
        icon: '💱',
        price: undefined,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '5 minutos',
        requirements: ['Cuenta activa con saldo suficiente', 'Identidad verificada'],
        tags: ['Tiempo real', 'Sin comisiones', 'Multi-divisa'],
        rating: 4.5,
        reviewCount: 876,
    },
    {
        id: 'svc-003',
        category: 'VENTA_DIVISAS',
        title: 'Venta de Divisas',
        description: 'Convierte tus monedas extranjeras a Soles peruanos.',
        longDescription: 'Vende tus dólares, euros u otras monedas y recibe Soles al mejor tipo de cambio disponible. El proceso es automático y el acreditamiento es inmediato en tu cuenta.',
        icon: '💰',
        price: undefined,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '5 minutos',
        requirements: ['Cuenta activa', 'Moneda extranjera disponible en billetera'],
        tags: ['Inmediato', 'Mejor tasa', 'Seguro'],
        rating: 4.6,
        reviewCount: 654,
    },
    {
        id: 'svc-004',
        category: 'ASESOR_FINANCIERO',
        title: 'Asesoría Financiera',
        description: 'Habla con un asesor financiero certificado vía WhatsApp.',
        longDescription: 'Conecta directamente con un asesor financiero certificado a través de WhatsApp. Recibe orientación personalizada sobre ahorro, inversión, manejo de deudas y planificación financiera. Sesiones de 30 minutos disponibles lunes a viernes.',
        icon: '🤝',
        price: 29.90,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '30 minutos',
        requirements: ['Número de WhatsApp verificado', 'Pago previa a la sesión'],
        tags: ['Personalizado', 'Certificado', 'WhatsApp'],
        rating: 4.9,
        reviewCount: 432,
    },
    {
        id: 'svc-005',
        category: 'PRESTAMOS_PERSONALES',
        title: 'Préstamos Personales',
        description: 'Solicita un préstamo personal con proceso rápido y sencillo.',
        longDescription: 'Obtén un préstamo personal en hasta 24 horas. Tasas de interés desde 1.5% mensual. Simula tu préstamo, elige el plazo que mejor se adapte a ti y solicítalo directamente desde la app. Se requiere score crediticio mínimo de 600.',
        icon: '💳',
        price: undefined,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '24 horas',
        requirements: ['Score crediticio ≥ 600', 'DNI vigente', 'Recibo de servicio último mes'],
        tags: ['Rápido', 'Flexible', 'Bajo interés'],
        rating: 4.3,
        reviewCount: 1087,
    },
    {
        id: 'svc-006',
        category: 'INVERSIONES',
        title: 'Fondos de Inversión',
        description: 'Invierte tu dinero en fondos gestionados por profesionales.',
        longDescription: 'Accede a fondos de inversión curados por profesionales. Opciones que van desde fondos de bajo riesgo (conservador) hasta alto riesgo (agresivo). Visualiza el rendimiento histórico, proyecciones y comisiones antes de invertir. Monto mínimo de inversión: S/. 100.',
        icon: '📊',
        price: undefined,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: 'Variable',
        requirements: ['Identidad verificada', 'Monto mínimo S/. 100', 'Contrato de inversión firmado'],
        tags: ['Profesional', 'Variado', 'Transparente'],
        rating: 4.4,
        reviewCount: 321,
    },
    {
        id: 'svc-007',
        category: 'SEGUROS',
        title: 'Seguros Personales',
        description: 'Protege tu vida, salud y bienes con seguros accesibles.',
        longDescription: 'Compara y contrata seguros personales desde la app. Disponibles seguros de vida, salud, hogar y auto. Primas mensuales desde S/. 15.00. El proceso de contratación es 100% digital, sin papeleo ni espera.',
        icon: '🛡️',
        price: 15.00,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '10 minutos',
        requirements: ['DNI vigente', 'Edad entre 18 y 70 años'],
        tags: ['Digital', 'Económico', 'Múltiples opciones'],
        rating: 4.2,
        reviewCount: 198,
    },
    {
        id: 'svc-008',
        category: 'DECLARACION_RENTA',
        title: 'Declaración de Renta',
        description: 'Prepara y presenta tu declaración de renta de forma sencilla.',
        longDescription: 'Un asesor experto prepara tu declaración de renta y te guía en cada paso del proceso. Incluye revisión de deducciones aplicables, cálculo de impuesto y presentación directa ante la SUNAT. Disponible durante el período de declaraciones y pre-declaraciones.',
        icon: '📋',
        price: 49.90,
        currency: 'PEN',
        status: 'DISPONIBLE',
        estimatedTime: '48 horas',
        requirements: ['Datos de SUNAT', 'Constancias de retención', 'Identificación personal'],
        tags: ['Expert', 'Integral', 'SUNAT'],
        rating: 4.7,
        reviewCount: 267,
    },
];
